/* INSERT DATA KhoaHoc */
INSERT INTO khoahoc(MaKhoaHoc,TenKhoaHoc,MoTaKhoaHoc,ThoiLuongKhoaHoc,GiangVien,MucDoKhoaHoc,SoLuongHocVienToiDa,GiaTien,NgayKhaiGiang,NgayBeGiang,DanhGiaKhoaHoc,TrangThaiKhoaHoc,MaLoaiKhoaHoc,TaoVaoLuc,TaoBoi,ChinhSuaLanCuoiVaoLuc,ChinhSuaLanCuoiBoi) VALUES 
('CRS1','IT Business Analysis','Khóa học IT Business Analysis, học viên sẽ được giảng dạy các kỹ năng cơ bản và công cụ phân tích kinh doanh, bao gồm thu thập và phân tích yêu cầu, mô hình hóa quy trình kinh doanh, xác định và giải quyết vấn đề, và quản lý dự án. Họ sẽ tìm hiểu về các phương pháp và kỹ thuật phân tích yêu cầu, cách thực hiện các cuộc phỏng vấn và phân tích tài liệu, cùng với việc sử dụng các công cụ và phần mềm hỗ trợ như Microsoft Visio, Excel, và các hệ thống quản lý yêu cầu.','36 giờ','Ryan Nguyễn','Người mới',42,4000000, '2023-02-22','2023-03-22',45,'Đang vận hành','CID1','2023-01-14 01:04:10','Hệ Thống','2023-01-15 06:38:49','Hệ Thống'),
('CRS2','Product Owner Master Class','Khóa học Product Owner Master Class là một chương trình đào tạo chuyên sâu dành cho những người muốn trở thành Product Owner chuyên nghiệp hoặc muốn nâng cao kỹ năng quản lý sản phẩm của mình. Khóa học này cung cấp kiến thức và công cụ cần thiết để thành công trong vai trò Product Owner trong một dự án phát triển phần mềm hoặc sản phẩm công nghệ.','54 giờ','Harry Phạm','Đã có kinh nghiệm',41,5400000, '2023-04-25','2023-06-10',4,'Đang vận hành','CID2','2023-02-23 14:32:22','Hệ Thống','2023-02-27 11:57:47','Hệ Thống'),
('CRS3','SQL Advanced Class','Khóa học SQL Advanced Class là một khóa học đào tạo chuyên sâu nhằm cung cấp kiến thức và kỹ năng cao cấp về ngôn ngữ truy vấn SQL (Structured Query Language). Khóa học này dành cho những người đã có kiến thức cơ bản về SQL và muốn nâng cao khả năng của mình trong việc truy vấn, phân tích và quản lý cơ sở dữ liệu.','192 giờ','Jerry Bùi','Đã có kinh nghiệm',31,4914000, '2023-06-28','2023-11-13',4,'Đang vận hành','CID3','2023-05-30 12:15:47','Hệ Thống','2023-06-12 11:26:18','Hệ Thống'),
('CRS4','Data Analysis','Khóa học Data Analysis là một chương trình đào tạo được thiết kế để giúp học viên nắm vững các kỹ năng và công cụ cần thiết để hiểu, phân tích và trích xuất thông tin từ dữ liệu. Khóa học này nhằm cung cấp kiến thức và kỹ năng cần thiết để học viên có thể làm việc với dữ liệu số, tạo ra thông tin hữu ích và đưa ra quyết định dựa trên dữ liệu.','144 giờ','Phil Phan','Người mới',45,4429000, '2023-10-05','2024-01-05',45,'Đang vận hành','CID4','2023-06-17 20:40:55','Hệ Thống','2023-08-20 02:06:10','Hệ Thống'),
('CRS5','Business Intelligence','Khóa học Business Intelligence là một chương trình đào tạo nhằm cung cấp kiến thức và kỹ năng cần thiết để hiểu, phân tích và sử dụng thông tin kinh doanh để hỗ trợ quyết định và phát triển chiến lược kinh doanh. Khóa học này tập trung vào việc sử dụng các công cụ và phương pháp phân tích dữ liệu để tạo ra thông tin quan trọng và đưa ra quyết định thông minh trong môi trường kinh doanh.','36 giờ','Anh Tú','Người mới',30,5482000, '2023-12-15','2024-01-15',35,'Đang vận hành','CID5','2023-07-21 21:14:47','Hệ Thống','2023-07-26 03:35:44','Hệ Thống'),
('CRS6','Excel Advanced Class','Khóa học Excel Advanced Class là một chương trình đào tạo nhằm cung cấp kiến thức và kỹ năng nâng cao về việc sử dụng Microsoft Excel, một trong những công cụ phổ biến nhất trong việc xử lý và phân tích dữ liệu. Khóa học này tập trung vào việc giúp học viên trở thành những người dùng thành thạo của Excel và khám phá các tính năng và công cụ phức tạp để tăng cường hiệu suất làm việc và tạo ra các báo cáo và phân tích chuyên sâu.','48 giờ','Ngọc Thu','Chuyên gia',33,4704000, '2023-03-28','2023-04-28',4,'Đang vận hành','CID4','2023-02-04 17:32:25','Hệ Thống','2023-02-04 17:32:25','Hệ Thống'),
('CRS7','Database Foundation Class','Khóa học Database Foundation Class là một chương trình đào tạo cung cấp kiến thức cơ bản về cơ sở dữ liệu và các khái niệm quan trọng liên quan đến quản lý dữ liệu. Khóa học này giúp học viên hiểu về cấu trúc, lưu trữ và truy xuất dữ liệu trong các hệ quản trị cơ sở dữ liệu (Database Management Systems - DBMS) như MySQL, Oracle, SQL Server và PostgreSQL.','180 giờ','Tony Lê','Người mới',29,5317000, '2023-05-22','2023-07-22',3,'Vô hiệu hóa','CID4','2023-03-16 18:04:40','Hệ Thống','2023-03-16 18:04:40','Hệ Thống'),
('CRS8','Desktop Coding Class','Khóa học Desktop Coding Class là một chương trình đào tạo nhằm giúp học viên học cách phát triển ứng dụng máy tính bằng việc sử dụng các ngôn ngữ lập trình và công cụ phát triển phần mềm trên máy tính. Khóa học này tập trung vào việc trang bị kiến thức và kỹ năng cần thiết để xây dựng ứng dụng chạy trên desktop, từ ứng dụng đơn giản đến các ứng dụng phức tạp.','174 giờ','Jennie Huỳnh','Người mới',35,4370000, '2023-12-15','2024-02-05',35,'Đang chiêu sinh','CID1','2023-08-05 18:26:46','Hệ Thống','2023-08-05 18:26:46','Hệ Thống'),
('CRS9','Python Advance Coding Class','Khóa học Python Advanced Coding Class là một chương trình đào tạo nhằm giúp học viên nâng cao kỹ năng lập trình Python và hiểu sâu về các khái niệm và kỹ thuật phức tạp trong ngôn ngữ này. Khóa học này tập trung vào các chủ đề tiên tiến và ứng dụng thực tế của Python, giúp học viên trở thành những lập trình viên Python chuyên nghiệp.','120 giờ','John Đặng','Đã có kinh nghiệm',36,4333000, '2023-11-20','2024-03-20',4,'Đang vận hành','CID1','2023-10-15 17:43:14','Hệ Thống','2023-10-15 17:43:14','Hệ Thống'),
('CRS10','Business Data Engineer','Khóa học "Business Data Engineer" là một chương trình đào tạo nhằm trang bị học viên với kiến thức và kỹ năng cần thiết để trở thành một chuyên gia trong lĩnh vực kỹ thuật dữ liệu kinh doanh. Khóa học này tập trung vào các khía cạnh kỹ thuật và công nghệ liên quan đến quản lý, xử lý và phân tích dữ liệu trong môi trường doanh nghiệp.','240 giờ','Tuấn Vũ','Chuyên gia',21,5265000, '2023-12-11','2024-05-11',45,'Đang vận hành','CID5','2023-11-15 12:23:56','Hệ Thống','2023-11-15 12:23:56','Hệ Thống');
